["github.com/BurntSushi/toml"]
  sumVersion = "v0.3.1"
  ["github.com/BurntSushi/toml".fetch]
    type = "git"
    url = "https://github.com/BurntSushi/toml"
    rev = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005"
    sha256 = "1fjdwwfzyzllgiwydknf1pwjvy49qxfsczqx5gz3y0izs7as99j6"

["github.com/alecthomas/assert"]
  sumVersion = "v0.0.0-20170929043011-405dbfeb8e38"
  ["github.com/alecthomas/assert".fetch]
    type = "git"
    url = "https://github.com/alecthomas/assert"
    rev = "405dbfeb8e38effee6e723317226e93fff912d06"
    sha256 = "1l567pi17k593nrd1qlbmiq8z9jy3qs60px2a16fdpzjsizwqx8l"

["github.com/alecthomas/colour"]
  sumVersion = "v0.0.0-20160524082231-60882d9e2721"
  ["github.com/alecthomas/colour".fetch]
    type = "git"
    url = "https://github.com/alecthomas/colour"
    rev = "60882d9e27213e8552dcff6328914fe4c2b44bc9"
    sha256 = "0iq566534gbzkd16ixg7fk298wd766821vvs80838yifx9yml5vs"

["github.com/alecthomas/kingpin"]
  sumVersion = "v2.2.6+incompatible"
  ["github.com/alecthomas/kingpin".fetch]
    type = "git"
    url = "https://github.com/alecthomas/kingpin"
    rev = "947dcec5ba9c011838740e680966fd7087a71d0d"
    sha256 = "0mndnv3hdngr3bxp7yxfd47cas4prv98sqw534mx7vp38gd88n5r"

["github.com/alecthomas/repr"]
  sumVersion = "v0.0.0-20180818092828-117648cd9897"
  ["github.com/alecthomas/repr".fetch]
    type = "git"
    url = "https://github.com/alecthomas/repr"
    rev = "117648cd9897bc621d6d52cd05727b9abdd5528a"
    sha256 = "05v1rgzdqc8razf702laagrvhvx68xd9yxxmzd3dyz0d6425pdrp"

["github.com/alecthomas/template"]
  sumVersion = "v0.0.0-20160405071501-a0175ee3bccc"
  ["github.com/alecthomas/template".fetch]
    type = "git"
    url = "https://github.com/alecthomas/template"
    rev = "a0175ee3bccc567396460bf5acd36800cb10c49c"
    sha256 = "0qjgvvh26vk1cyfq9fadyhfgdj36f1iapbmr5xp6zqipldz8ffxj"

["github.com/alecthomas/units"]
  sumVersion = "v0.0.0-20151022065526-2efee857e7cf"
  ["github.com/alecthomas/units".fetch]
    type = "git"
    url = "https://github.com/alecthomas/units"
    rev = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a"
    sha256 = "1j65b91qb9sbrml9cpabfrcf07wmgzzghrl7809hjjhrmbzri5bl"

["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/google/renameio"]
  sumVersion = "v0.1.0"
  ["github.com/google/renameio".fetch]
    type = "git"
    url = "https://github.com/google/renameio"
    rev = "f0e32980c006571efd537032e5f9cd8c1a92819e"
    sha256 = "1ki2x5a9nrj17sn092d6n4zr29lfg5ydv4xz5cp58z6cw8ip43jx"

["github.com/kisielk/gotool"]
  sumVersion = "v1.0.0"
  ["github.com/kisielk/gotool".fetch]
    type = "git"
    url = "https://github.com/kisielk/gotool"
    rev = "80517062f582ea3340cd4baf70e86d539ae7d84d"
    sha256 = "14af2pa0ssyp8bp2mvdw184s5wcysk6akil3wzxmr05wwy951iwn"

["github.com/kr/pretty"]
  sumVersion = "v0.1.0"
  ["github.com/kr/pretty".fetch]
    type = "git"
    url = "https://github.com/kr/pretty"
    rev = "73f6ac0b30a98e433b289500d779f50c1a6f0712"
    sha256 = "18m4pwg2abd0j9cn5v3k2ksk9ig4vlwxmlw9rrglanziv9l967qp"

["github.com/kr/pty"]
  sumVersion = "v1.1.1"
  ["github.com/kr/pty".fetch]
    type = "git"
    url = "https://github.com/kr/pty"
    rev = "282ce0e5322c82529687d609ee670fac7c7d917c"
    sha256 = "0383f0mb9kqjvncqrfpidsf8y6ns5zlrc91c6a74xpyxjwvzl2y6"

["github.com/kr/text"]
  sumVersion = "v0.1.0"
  ["github.com/kr/text".fetch]
    type = "git"
    url = "https://github.com/kr/text"
    rev = "e2ffdb16a802fe2bb95e2e35ff34f0e53aeef34f"
    sha256 = "1gm5bsl01apvc84bw06hasawyqm4q84vx1pm32wr9jnd7a8vjgj1"

["github.com/mattn/go-isatty"]
  sumVersion = "v0.0.3"
  ["github.com/mattn/go-isatty".fetch]
    type = "git"
    url = "https://github.com/mattn/go-isatty"
    rev = "0360b2af4f38e8d38c7fce2a9f4e702702d73a39"
    sha256 = "06w45aqz2a6yrk25axbly2k5wmsccv8cspb94bfmz4izvw8h927n"

["github.com/orivej/e"]
  sumVersion = "v0.0.0-20180728214217-ac3492690fda"
  ["github.com/orivej/e".fetch]
    type = "git"
    url = "https://github.com/orivej/e"
    rev = "ac3492690fda471c5eab817efd86badf5c3ac158"
    sha256 = "11jizr28kfkr6zscjxg95pqi6cjp08aqnhs41sdhc98nww78ilkr"

["github.com/orivej/go-nix"]
  sumVersion = "v0.0.0-20180830055821-dae45d921a44"
  ["github.com/orivej/go-nix".fetch]
    type = "git"
    url = "https://github.com/orivej/go-nix"
    rev = "dae45d921a44e6ec05b4ea2b00d8e9efadf770c3"
    sha256 = "17hfmsz8hs3h2d5c06j1bvbw8ijrhzm3iz911z5zydsl4x7y0cgy"

["github.com/pkg/errors"]
  sumVersion = "v0.8.1"
  ["github.com/pkg/errors".fetch]
    type = "git"
    url = "https://github.com/pkg/errors"
    rev = "ba968bfe8b2f7e042a574c888954fccecfa385b4"
    sha256 = "0g5qcb4d4fd96midz0zdk8b9kz8xkzwfa8kr1cliqbg8sxsy5vd1"

["github.com/pkg/profile"]
  sumVersion = "v1.2.1"
  ["github.com/pkg/profile".fetch]
    type = "git"
    url = "https://github.com/pkg/profile"
    rev = "5b67d428864e92711fcbd2f8629456121a56d91f"
    sha256 = "0blqmvgqvdbqmh3fp9pfdxc9w1qfshrr0zy9whj0sn372bw64qnr"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/rogpeppe/go-internal"]
  sumVersion = "v1.3.0"
  ["github.com/rogpeppe/go-internal".fetch]
    type = "git"
    url = "https://github.com/rogpeppe/go-internal"
    rev = "438578804ca6f31be148c27683afc419ce47c06e"
    sha256 = "0mcdh1licgnnahwml9y2iq6xy5x9xmjw5frcnds2s3wpjyqrl216"

["github.com/sergi/go-diff"]
  sumVersion = "v1.0.0"
  ["github.com/sergi/go-diff".fetch]
    type = "git"
    url = "https://github.com/sergi/go-diff"
    rev = "1744e2970ca51c86172c8190fadad617561ed6e7"
    sha256 = "0swiazj8wphs2zmk1qgq75xza6m19snif94h2m6fi8dqkwqdl7c7"

["github.com/sirupsen/logrus"]
  sumVersion = "v1.7.0"
  ["github.com/sirupsen/logrus".fetch]
    type = "git"
    url = "https://github.com/sirupsen/logrus"
    rev = "6699a89a232f3db797f2e280639854bbc4b89725"
    sha256 = "1a59pw7zimvm8k423iq9l4f4qjj1ia1xc6pkmhwl2mxc46y2n442"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.4.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "221dbe5ed46703ee255b1da0dec05086f5035f62"
    sha256 = "187i5g88sxfy4vxpm7dw1gwv29pa2qaq475lxrdh5livh69wqfjb"

["github.com/tweag/gomod2nix"]
  sumVersion = "v0.0.0-20210329153857-c78d7b9f15a2"
  ["github.com/tweag/gomod2nix".fetch]
    type = "git"
    url = "https://github.com/tweag/gomod2nix"
    rev = "c78d7b9f15a24eba95fbc228509f513c83709d8b"
    sha256 = "15qjp1g2pkkpr5b1mfjfiwl8kyfabi66hklk7apk7jh9sb2qqf85"

["go.uber.org/atomic"]
  sumVersion = "v1.6.0"
  ["go.uber.org/atomic".fetch]
    type = "git"
    url = "https://github.com/uber-go/atomic"
    rev = "845920076a298bdb984fb0f1b86052e4ca0a281c"
    sha256 = "0pcshhrg1ajfh04rk0sf8805isizbb2m35js5c9gbbh2cjg3c7h5"

["go.uber.org/multierr"]
  sumVersion = "v1.5.0"
  ["go.uber.org/multierr".fetch]
    type = "git"
    url = "https://github.com/uber-go/multierr"
    rev = "b587143a48b62b01d337824eab43700af6ffe222"
    sha256 = "0xgfmyzwfr3l0gi3024g6hj1x1pbq2c9aszgww43drvb0myqzh5w"

["go.uber.org/tools"]
  sumVersion = "v0.0.0-20190618225709-2cfd321de3ee"
  ["go.uber.org/tools".fetch]
    type = "git"
    url = "https://github.com/uber-go/tools"
    rev = "2cfd321de3ee5d5f8a5fda2521d1703478334d98"
    sha256 = "0kcsg9pd3vyp5v9dz8xzd9lkpbqrlhr1rv6hg38afq6ifziw319i"

["go.uber.org/zap"]
  sumVersion = "v1.15.0"
  ["go.uber.org/zap".fetch]
    type = "git"
    url = "https://github.com/uber-go/zap"
    rev = "feeb9a050b31b40eec6f2470e7599eeeadfe5bdd"
    sha256 = "15av5vjpxkvadbzisdbjqk6z860gnd3lvi6qslwl0ixi8gk23jr0"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20191011191535-87dc89f01550"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "87dc89f01550277dc22b74ffcf4cd89fa2f40f4c"
    sha256 = "0z4i1m2yn3f31ci7wvcm2rxkx2yiv7a78mfzklncmsz2k97rlh2g"

["golang.org/x/lint"]
  sumVersion = "v0.0.0-20190930215403-16217165b5de"
  ["golang.org/x/lint".fetch]
    type = "git"
    url = "https://go.googlesource.com/lint"
    rev = "16217165b5de779cb6a5e4fc81fa9c1166fda457"
    sha256 = "0jhwmwc0vykcmf164na0pnadl8gv7184b6pf3xayknwmzdw6vd7h"

["golang.org/x/mod"]
  sumVersion = "v0.3.0"
  ["golang.org/x/mod".fetch]
    type = "git"
    url = "https://go.googlesource.com/mod"
    rev = "859b3ef565e237f9f1a0fb6b55385c497545680d"
    sha256 = "0ldgbx2zpprbsfn6p8pfgs4nn87gwbfcv2z0fa7n8alwsq2yw78q"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20190620200207-3b0461eec859"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "3b0461eec859c4b73bb64fdc8285971fd33e3938"
    sha256 = "0l00c8l0a8xnv6qdpwfzxxsr58jggacgzdrwiprrfx2xqm37b6d5"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20190423024810-112230192c58"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "112230192c580c3556b8cee6403af37a4fc5f28c"
    sha256 = "05i2k43j2d0llq768hg5pf3hb2yhfzp9la1w5wp0rsnnzblr0lfn"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20191026070338-33540a1f6037"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "33540a1f603772f9d4b761f416f5c10dade23e96"
    sha256 = "0fjcv0vzvi6za0b4xmnk3932pr9f9gczzf03y0kgq3ry9rqg169y"

["golang.org/x/text"]
  sumVersion = "v0.3.0"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "f21a4dfb5e38f5895301dc265a8def02365cc3d0"
    sha256 = "0r6x6zjzhr8ksqlpiwm5gdd7s209kwk5p4lw54xjvz10cs3qlq19"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20191119224855-298f0cb1881e"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "298f0cb1881e71e68bc5bc17757fabe78a426460"
    sha256 = "0l4pqwib2wnfnix6nvxl0yrq87ipi7ff1rz6z5bxfzy9dki1nzmv"

["golang.org/x/xerrors"]
  sumVersion = "v0.0.0-20191011141410-1b5146add898"
  ["golang.org/x/xerrors".fetch]
    type = "git"
    url = "https://go.googlesource.com/xerrors"
    rev = "1b5146add8981d58be77b16229c0ff0f8bebd8c1"
    sha256 = "0w2akj91krxjag0xdhsg78470888nicc5ismc2ap9jqpss6v1zih"

["gopkg.in/check.v1"]
  sumVersion = "v1.0.0-20180628173108-788fd7840127"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "788fd78401277ebd861206a03c884797c6ec5541"
    sha256 = "0v3bim0j375z81zrpr5qv42knqs0y2qv2vkjiqi5axvb78slki1a"

["gopkg.in/errgo.v2"]
  sumVersion = "v2.1.0"
  ["gopkg.in/errgo.v2".fetch]
    type = "git"
    url = "https://gopkg.in/errgo.v2"
    rev = "f768c5ab0476c50e978b039312180859c10fe8c0"
    sha256 = "065mbihiy7q67wnql0bzl9y1kkvck5ivra68254zbih52jxwrgr2"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.2.2"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "51d6538a90f86fe93ac480b35f37b2be17fef232"
    sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa"

["honnef.co/go/tools"]
  sumVersion = "v0.0.1-2019.2.3"
  ["honnef.co/go/tools".fetch]
    type = "git"
    url = "https://github.com/dominikh/go-tools"
    rev = "afd67930eec2a9ed3e9b19f684d17a062285f16a"
    sha256 = "1rwwahmbs4dwxncwjj56likir1kps9937vm2id3rygxzzla40zal"
