schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v0.3.1"
    hash = "sha256-Rqak1dE/Aj/+Kx1/pl3Hifgt+Q3OzuZ5fJR+/x3nTbo="
  [mod."github.com/alecthomas/assert"]
    version = "v0.0.0-20170929043011-405dbfeb8e38"
    hash = "sha256-FHXMf9Ty3+ZMUKJfYDQeXqaPcKyL4tCyHanME+I9ptA="
  [mod."github.com/alecthomas/colour"]
    version = "v0.0.0-20160524082231-60882d9e2721"
    hash = "sha256-ehdafeouejQQQHrvIJAxp3GUxHTn9WhCm389MooxBUc="
  [mod."github.com/alecthomas/kingpin"]
    version = "v2.2.6+incompatible"
    hash = "sha256-uViE2kPj7tMrGYVjjdLOl2jFDmmu+3P7GvnZBse2zVY="
  [mod."github.com/alecthomas/repr"]
    version = "v0.0.0-20180818092828-117648cd9897"
    hash = "sha256-N7dbBDENfN9G+7V3n1pHpm+481OKCnDcVxkx3P7LYRc="
  [mod."github.com/alecthomas/template"]
    version = "v0.0.0-20160405071501-a0175ee3bccc"
    hash = "sha256-sjuHfqM34m9uL7muq2JwZsj2HPRNuYSdZ2FuI+DeT2I="
  [mod."github.com/alecthomas/units"]
    version = "v0.0.0-20151022065526-2efee857e7cf"
    hash = "sha256-dJWY/6oZSgkTQIdm+P5/lR/gWHZLXZZozUunhUNaxcg="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/google/renameio"]
    version = "v0.1.0"
    hash = "sha256-XQ5yI+LMfFQuK7+T3Xx5jiaRP7GmiQSsPkFmm1TpIs4="
  [mod."github.com/kisielk/gotool"]
    version = "v1.0.0"
    hash = "sha256-lsdQkue8gFz754PGqczUnvGiCQq87SruQtdrDdQVTpE="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/kr/pty"]
    version = "v1.1.1"
    hash = "sha256-AVeS+ivwNzIrgWQaLtsmO2f2MYGpxIVqdac/EzaYI1Q="
  [mod."github.com/kr/text"]
    version = "v0.1.0"
    hash = "sha256-QT65kTrNypS5GPWGvgnCpGLPlVbQAL4IYvuqAKhepb4="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.3"
    hash = "sha256-9ogEEd8/kl/dImldzdBmTFdepvB0dVXEzN4o8bEqhBs="
  [mod."github.com/orivej/e"]
    version = "v0.0.0-20180728214217-ac3492690fda"
    hash = "sha256-edKIDucWJQabDkRDixUCVzIT8S3pdcn0N3m6iUT+UYY="
  [mod."github.com/orivej/go-nix"]
    version = "v0.0.0-20180830055821-dae45d921a44"
    hash = "sha256-/jHgTydUN//LDyH9OOqHWUbE115BGsBKE3BoiL6uDp4="
  [mod."github.com/pkg/errors"]
    version = "v0.8.1"
    hash = "sha256-oe3iddfoLRwpC3ki5fifHf2ZFprtg99iNak50shiuDw="
  [mod."github.com/pkg/profile"]
    version = "v1.2.1"
    hash = "sha256-2WJi+BJnWA0k5Ml/kDPUDgeeWG/upusGrHi1jd+umC4="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.3.0"
    hash = "sha256-JgiasZeXDy10syy7wmXtqRffDY7CJ1o5VNY+FmmAjVU="
  [mod."github.com/sergi/go-diff"]
    version = "v1.0.0"
    hash = "sha256-I8rbJFKm44u/wS/gz+2yX9882xXcBdb9mKEKq5OoJRU="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.7.0"
    hash = "sha256-VClDP4DJDdMFTMGWR7I8L4hQRMU7cOphLRyUfxCvnNY="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.0"
    hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="
  [mod."github.com/stretchr/testify"]
    version = "v1.4.0"
    hash = "sha256-yJw5uyO9WCd1/fxFK/1fYch8WKKALoqVFENX8Nt92fY="
  [mod."github.com/tweag/gomod2nix"]
    version = "v0.0.0-20210329153857-c78d7b9f15a2"
    hash = "sha256-VYPwHfkgWNXDKaBbj9Jb/2SYwJLGYfOLQS/K9nyePdQ="
  [mod."go.uber.org/atomic"]
    version = "v1.6.0"
    hash = "sha256-BR42nmQCrvUSK1qWUcVaP+pYAEJOg5kJgE6q8DKEml0="
  [mod."go.uber.org/multierr"]
    version = "v1.5.0"
    hash = "sha256-vMCPfQVr5zYI5+9rlZjA64YeJDSPCDDiA3Rkx7+v7nU="
  [mod."go.uber.org/tools"]
    version = "v0.0.0-20190618225709-2cfd321de3ee"
    hash = "sha256-vLL9lT4iMxODR5+I6ZS14V4WcEd7REPNYZt0pCdNKLM="
  [mod."go.uber.org/zap"]
    version = "v1.15.0"
    hash = "sha256-JCzUvn9PEi4LmBdHMrZQ+pMtE8e/qT2Lx8ZG1yHFeXQ="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20191011191535-87dc89f01550"
    hash = "sha256-T0CaT5ri68osnd9VdNTZ0Ys+exaVbX4iC8MN60UNkXw="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20190930215403-16217165b5de"
    hash = "sha256-8LRtePuV2+lVH+6aRVA4+yHalL1AWWKCq2z6DRivHEo="
  [mod."golang.org/x/mod"]
    version = "v0.3.0"
    hash = "sha256-c+KKzeDUDxrKIx8un1DpETlTK+DmHP+zUjRZrgs0ejo="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20190620200207-3b0461eec859"
    hash = "sha256-lVNbp7zOBVbvzA1fFR4SkUskYfAMt2eILoWuDgk0oS4="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20190423024810-112230192c58"
    hash = "sha256-1lGQ6frW6gwuLzwomu530IsFh7vlQWQOphQ0IQeZIhY="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20191026070338-33540a1f6037"
    hash = "sha256-AZ5uAOCO9wPxif2h4mE0twivtnKCQMKVLvg2CARWYp8="
  [mod."golang.org/x/text"]
    version = "v0.3.0"
    hash = "sha256-0FFbaxF1ZuAQF3sCcA85e8MO6prFeHint36inija4NY="
  [mod."golang.org/x/tools"]
    version = "v0.0.0-20191119224855-298f0cb1881e"
    hash = "sha256-xhp3MWK3dr+PJgfOGaFAURPdw/ar+GRb+wHBnCG8Tg0="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20191011141410-1b5146add898"
    hash = "sha256-MP6wjdYXy3SVYFXHwli0CCFwCDpPw9bBU7LnGZKcSnA="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20180628173108-788fd7840127"
    hash = "sha256-KsRJNTprd1UijnJusbHwQGM7Bdm45Jt/QL+cIUGNa2w="
  [mod."gopkg.in/errgo.v2"]
    version = "v2.1.0"
    hash = "sha256-Ir/MuxQFxvVJEciovGOZbM8ZfKJ/AYotPwYfH2FctRg="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.2"
    hash = "sha256-SjNLmGSxoYabOi/zdjymW3mSgaxaS39btBQ3/aUIkgc="
  [mod."honnef.co/go/tools"]
    version = "v0.0.1-2019.2.3"
    hash = "sha256-jpCzv1UG8xGB44IA+kcAXDULYQlJWqa816GYP+BQoMs="
